name: Build javacpp-presets/opencv for L4T Orin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd l4t-orin
          bash build.sh