name: Build javacpp-presets/opencv for Linux x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd linux-x86_64
          bash build.sh