name: Build javacpp-presets/opencv for Windows x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [windows-2022]
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.24
        id: cuda-toolkit
        with:
          cuda: '12.9.0'
      - name: Install cuDNN
        shell: cmd
        run: |
          curl -LO https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/windows-x86_64/cudnn-windows-x86_64-9.9.0.52_cuda12-archive.zip
          unzip cudnn-windows-x86_64-9.9.0.52_cuda12-archive.zip
          move cudnn-windows-x86_64-9.9.0.52_cuda12-archive\bin\*.dll "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v12.9\bin"
          move cudnn-windows-x86_64-9.9.0.52_cuda12-archive\include\*.h "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v12.9\include"
          move cudnn-windows-x86_64-9.9.0.52_cuda12-archive\lib\x64\*.lib "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v12.9\lib\x64"
      - name: Remove broken stuff
        shell: cmd
        run: |
          echo Removing broken stuff from WSL, MSYS2, etc
          rm "C:/msys64/usr/bin/curl.exe" "C:/msys64/mingw32/bin/curl.exe" "C:/msys64/mingw64/bin/curl.exe"
          rm "C:/WINDOWS/system32/bash.EXE" "C:/msys64/usr/bin/link.exe" "C:/msys64/usr/bin/timeout.exe" "C:/msys64/usr/bin/python.exe" "C:/msys64/usr/bin/python3.exe"
          rm "C:/ProgramData/chocolatey/bin/gfortran.exe" "C:/msys64/mingw32/bin/gfortran.exe" "C:/msys64/mingw32/bin/python.exe" "C:/msys64/mingw32/bin/python3.exe"
          rm "C:/Strawberry/c/bin/gfortran.exe" "C:/msys64/mingw64/bin/gfortran.exe" "C:/msys64/mingw64/bin/python.exe" "C:/msys64/mingw64/bin/python3.exe"
          rm "C:/msys64/mingw32/bin/clang-cl.exe" "C:/msys64/mingw64/bin/clang-cl.exe" "C:/msys64/mingw32/bin/cmake.exe" "C:/msys64/mingw64/bin/cmake.exe"
          rm "C:/Strawberry/c/lib/libz.a" "C:/Strawberry/c/lib/libzlib.a" "C:/Strawberry/c/lib/libzdll.a" "C:/Strawberry/c/bin/cmake.exe"
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2022
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '8'
      - uses: actions/checkout@v4
      - name: Compile native library
        shell: cmd
        run: |
          cd windows-x86_64
          C:\msys64\usr\bin\bash build.sh
