name: Build javacpp-presets/opencv for Windows x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [windows-2022]
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.24
        id: cuda-toolkit
        with:
          cuda: '12.9.0'
      - name: Install cuDNN
        shell: bash
        run: |
          CUDNN_URL="https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/windows-x86_64/cudnn-windows-x86_64-9.9.0.52_cuda12-archive.zip"
          curl -L -o cudnn.zip "$CUDNN_URL"
          unzip cudnn.zip -d cudnn-temp
          CUDA_PATH="/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.9"
          cp cudnn-temp/cudnn-windows-x86_64-9.9.0.52_cuda12-archive/bin/*.dll "$CUDA_PATH/bin"
          cp cudnn-temp/cudnn-windows-x86_64-9.9.0.52_cuda12-archive/include/*.h "$CUDA_PATH/include"
          cp cudnn-temp/cudnn-windows-x86_64-9.9.0.52_cuda12-archive/lib/x64/*.lib "$CUDA_PATH/lib/x64"
          rm -rf cudnn.zip cudnn-temp
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Clone repo to D drive
        shell: powershell
        run: |
          Set-Location D:\
          git clone https://github.com/${{ github.repository }} b
      - name: Build javacpp-presets/opencv
        shell: cmd
        run: |
          cd D:\b\windows-x86_64
          "C:\Program Files\Git\bin\bash.exe" build.sh
