name: Build javacpp-presets/opencv for Windows x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [windows-2022]
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.24
        id: cuda-toolkit
        with:
          cuda: '12.9.0'
      - name: Install cuDNN
        shell: cmd
        run: |
          curl -LO https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/windows-x86_64/cudnn-windows-x86_64-9.9.0.52_cuda12-archive.zip
          unzip cudnn-windows-x86_64-9.9.0.52_cuda12-archive.zip
          move cudnn-windows-x86_64-9.9.0.52_cuda12-archive\bin*.dll "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v12.9\bin"
          move cudnn-windows-x86_64-9.9.0.52_cuda12-archive\include*.h "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v12.9\include"
          move cudnn-windows-x86_64-9.9.0.52_cuda12-archive\lib\x64*.lib "%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v12.9\lib\x64"
          "C:\Program Files\Git\bin\bash.exe" -c "rm -Rf ./cudnn-windows-x86_64-9.9.0.52_cuda12-archive.zip ./cudnn-windows-x86_64-9.9.0.52_cuda12-archive"
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2022
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Clone repo to D drive
        shell: powershell
        run: |
          Set-Location D:\
          git clone https://github.com/${{ github.repository }} b
      - name: Build javacpp-presets/opencv
        shell: cmd
        run: |
          cd D:\b\windows-x86_64
          "C:\Program Files\Git\bin\bash.exe" build.sh
